Develop
iliaKulakov/CompanyDirectoryCsv pull request #2
Opened 2018-05-13 19:43 UTC by iliaKulakov

2018-05-14 05:42 UTC, rmuhamedgaliev requested changes
необходимо править.

2018-05-14 05:42 UTC, rmuhamedgaliev commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Обычно папку .idea можно добавлять .gitignore. В виде синтаксиса .idea/

2018-05-14 05:42 UTC, rmuhamedgaliev commented on src/main/java/App.java
> +          //  System.out.println(new App().getGreeting());
Нарушено форматирование. Используй автоматичесике средства форматирования в IDE. https://www.jetbrains.com/help/idea/using-code-editor.html. Можно же сразу в IDE коммитить. https://www.jetbrains.com/help/idea/using-git-integration.html

2018-05-14 05:42 UTC, rmuhamedgaliev commented on src/main/java/Scanner/IScannerCsv.java
> +    void toReadFromFile2()throws FileNotFoundException;
В названии методов лучше не использовать цифры.

2018-05-14 05:42 UTC, rmuhamedgaliev commented on src/main/java/Scanner/ScannerCsv.java
> +                System.out.println("Line from file[" + lineFromFile[0] + lineFromFile[1] + lineFromFile[2] + lineFromFile[3] + lineFromFile[4] + lineFromFile[5]);
Конкатенация строк это зло. https://help.semmle.com/wiki/display/JAVA/String+concatenation+in+loop. лучше билдер и буффер использовать.

2018-05-14 05:42 UTC, rmuhamedgaliev commented on src/main/java/Scanner/ScannerCsv.java
> +            if (br != null) {
для этого еcть autocloseable resources. https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html. Безопастнее и кода меньше.

2018-05-14 05:42 UTC, rmuhamedgaliev commented on src/main/java/Scanner/ScannerCsv.java
> +                    if (index == 0)
очень много if, лучше разбить или заменить на свитч.

2018-05-14 05:42 UTC, rmuhamedgaliev commented on src/main/java/Scanner/ScannerCsv.java
> +        if (br != null) {
Уже писал выше.

2018-05-14 18:18 UTC, rmuhamedgaliev commented
@iliaKulakov у тебя при запуске ошибка не корректная. Смотри пример. 

```java
Please select menu item from keyboard: 
1 - Download file
2 - Search clients
3 - Sort clients
Enter a number here: 
1
Вы ввели число 1 - Загрузка файла 
Error in main method
```

2018-05-14 18:43 UTC, rmuhamedgaliev commented
@iliaKulakov неверно парсит файл. 

Вводные данные:

> Иванов Иван Иванович; 18.06.1983; 34; 6,45; "Работал над проектами: ""АБС""; ""КВД"""

```bash
[PersonStorage{ФИО=' 18.06.1983', Дата= 34, Количество проектов= 6,45, Рейтинг= "Работал над проектами: ""АБС"", Комментарии=' ""КВД"""'}]
Please select menu item from keyboard: 
1 - Download file
2 - Search clients
3 - Sort clients
Enter a number here: 
```

2018-05-14 18:55 UTC, rmuhamedgaliev commented on src/main/java/App.java
> +           // ScannerCsv readFromFile = new ScannerCsv();
Зачем в коде хранить комментарии это запах кода https://refactoring.guru/ru/smells/dead-code. Удаляй все ненужное.

2018-05-14 18:55 UTC, rmuhamedgaliev commented on src/main/java/Scanner/ScannerCsv.java
> +        String csvFile = "C:\\Users\\Angron\\Desktop\\csv\\test2.csv";
@iliaKulakov опять тут харкод. Низк так делать. Меняй на относительные пути или принимай путь от пользователя.

2018-05-14 18:55 UTC, rmuhamedgaliev commented on src/main/java/menuPackage/MainMenu.java
> +        this.items.add("Download file");
Я бы переназвал `Download File` не очень понятно. Например на `Load File`

2018-05-14 18:55 UTC, rmuhamedgaliev commented on src/main/java/storage/PersonStorage.java
> +public class PersonStorage {
Я бы назвал person и сделал ему паттерн builder либо сразу бы использовал конструктор. https://habr.com/post/244521/

2018-05-16 04:02 UTC, iliaKulakov commented on src/main/java/menuPackage/MainMenu.java
> +        this.items.add("Download file");
сделал

2018-05-16 21:32 UTC, iliaKulakov commented on src/main/java/storage/PersonStorage.java
> +public class PersonStorage {
Сделал, отдельный класс Person по паттерну Builder думаю как корректнее его использовать

2018-05-16 22:02 UTC, iliaKulakov commented on src/main/java/storage/PersonStorage.java
> +public class PersonStorage {
При парсинге проблемы когда делаю парсинг чего то отличного от String ошибки возникают когда в другом формате

2018-05-16 22:09 UTC, iliaKulakov commented on src/main/java/Scanner/ScannerCsv.java
> +                    if (index == 0)
Может мне вообще все чтение , через буффер ридер делать вместо сканера?

2018-05-19 10:29 UTC, merged

2018-05-19 10:29 UTC, iliaKulakov commented on src/main/java/Scanner/ScannerCsv.java
> +                System.out.println("Line from file[" + lineFromFile[0] + lineFromFile[1] + lineFromFile[2] + lineFromFile[3] + lineFromFile[4] + lineFromFile[5]);
Удалил этот класс вообще. Все в другом делаю

2018-05-19 10:30 UTC, iliaKulakov commented on src/main/java/Scanner/ScannerCsv.java
> +            if (br != null) {
Удалил этот класс вообще
Ссылку изучу